# Generated by Django 4.2.6 on 2023-10-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_music_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
