# Generated by Django 4.2.6 on 2023-10-23 17:32

import core.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_music_time_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(upload_to='musics', validators=[core.validator.audio_validation]),
        ),
    ]
