# Generated by Django 4.2.6 on 2023-11-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_music_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='cover_images/'),
        ),
    ]
