# Generated by Django 4.2.6 on 2023-11-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_music_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover_image',
            field=models.ImageField(upload_to='cover_images/'),
        ),
    ]
