# Generated by Django 4.2.6 on 2023-11-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_music_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
